version: '3'
services:
  redis: 
    image: redis

  web:
    depends_on: 
      - redis
    build: .
    ports:
      - "5000:3000"
    command: npm start
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    image: acestar01/user-api