version: '3'
services:
  redis: 
    image: redis
    volumes:
      - myapp:/data

  node-app:
    depends_on: 
      - redis
    build: .
    ports:
      - "5000:8080"
    command: npm start
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379


volumes:
  myapp: