---
- hosts: nodejs_server
  # Run commands as root
  become: true
  # Roles to be executed on these hosts
  roles:
  - role: nodejs/install
    tags: install

  - role: gitlab/healthchecks
    tags: check
