name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest

    defaults: 
      run:
        working-directory: ./user-api

    strategy:
      matrix:
        node-version: [16.x]
        redis-version: [4, 5, 6]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Start Redis
        uses: supercharge/redis-github-action@1.4.0
        with:
          redis-version: ${{ matrix.redis-version }}


      - run: npm install
      - run: npm run build --if-present
      - run: npm test
